PREFIX schema: <http://datadock.io/kal/data/id/definition/>
PREFIX stations: <http://datadock.io/kal/data/id/dataset/tokyo_metro_stations.csv#>

SELECT ?station_name ?station_name_english
WHERE {
  BIND ("Ginza Line" AS ?line_name_english)
  ?line schema:line_name_english ?line_name_english .
  ?s stations:on_line ?line .
  ?s schema:station_name ?station_name .
  ?s schema:station_name_english ?station_name_english .
}
