CONSTRUCT {
  ?s ?p ?o
}
WHERE {
    {
        SERVICE <https://dbpedia.org/sparql> {
            BIND (<http://dbpedia.org/resource/Bob_Dylan> AS ?s)
            ?s ?p ?o .
      }
    }
    UNION
    {
        SERVICE <https://query.wikidata.org/bigdata/namespace/wdq/sparql> {
            BIND (<http://www.wikidata.org/entity/Q392> AS ?s)
            ?s ?p ?o .
        }
    }
}
